#![enable(implicit_some)]
(
    border_width: 2,
    margin: [4, 4],
    workspace_margin: None,
    default_width: None,
    default_height: None,
    always_float: None,
    gutter: None,
    default_border_color: "{background}",
    floating_border_color: "{color6}",
    focused_border_color: "{foreground}",
    on_new_window: None,
)
