#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

leftwm-command "UnloadTheme"

pkill polybar
#while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
pkill compton
pkill picom
pkill sxhkd
pkill nm-applet
pkill pamac-tray
pkill xfce4-power-manager
pkill blueberry-tray
pkill polkit-gnome-authentication-agent-1
pkill xfce4-notifyd
pkill xfce4-clipman
pkill flameshot