[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 0

[[repos.themes]]
name = "genesis"
version = "1.0.0"
leftwm_versions = ">=0.3.0"
current = true

[[repos]]
url = "https://raw.githubusercontent.com/AnthonyMichaelTDM/leftwm-personal-themes/main/known.toml"
name = "Genesis Repo"
definitions_version = 1

[[repos.themes]]
name = "master-pywal-theme"
repository = "https://github.com/AnthonyMichaelTDM/master-pywal-theme/"
commit = "*"
version = "2.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "mpt-tablet"
repository = "https://github.com/AnthonyMichaelTDM/mpt-tablet/"
commit = "*"
version = "2.0.0"
leftwm_versions = "*"
current = false
