[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 1
themes = []

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 0

[[repos.themes]]
name = "candy"
version = "2.4.1"
leftwm_versions = "*"
current = true

[[repos]]
url = "https://raw.githubusercontent.com/arcolinux/arcolinux-leftwm-themes/master/known.toml"
name = "arcolinux"
definitions_version = 0
themes = []

[[repos]]
url = "https://raw.githubusercontent.com/arcolinux/arcolinux-leftwm-themes-community/main/known.toml"
name = "arcolinux-community"
definitions_version = 0
themes = []

[[repos]]
url = "https://raw.githubusercontent.com/AnthonyMichaelTDM/leftwm-personal-themes/main/known.toml"
name = "Personal"
definitions_version = 1
themes = []
